version: 2
updates:
  - package-ecosystem: "npm"
    directory: "vuet-docs"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
